### ISSUE TITLE
[D:]Help with making module

### ISSUE THREAD

**Issue by NekoKamiDesu** [mrkno/Kassy#123]
I'm not sure how making modules work and would like some guidance.
i.e. language to learn etc.

P.S. Trying to make a module that replies with a random selection from an array, and i need help; If anyone can make a module/write the code please do!

**Comment by mrkno** [comment]
There is fairly detailed documentation and a HelloWorld example of how to make a module [here](https://github.com/mrkno/Kassy/blob/master/doc/ModuleCreation.md).

The language of modules is Javascript as Kassy is written in node. It is also possible to bootstrap coffeescript with some additional difficulty if you want to try.

Basic idea:
- Create a directory in the modules directory that contains 2 files (`kassy.json` and `yourmodulename.js`)
- Add the `match` method to `yourmodulename.js`: tells kassy when to run your module
- Add the `help` method to ``yourmodulename.js`: tells kassy what to say when the help command is run
- Add the `run` method to `yourmodulename.js`: tells kassy what to do when the module is run
- Modify `kassy.json` to have the required details

For examples of implementations I strongly recommend looking at the HelloKassy example from the documentation and/or existing modules in the modules directory.

**Comment by NekoKamiDesu** [comment]
Cool thanks
