### ISSUE TITLE
Unknown mode 'debug'

### ISSUE THREAD

**Issue by NekoKamiDesu** [mrkno/Kassy#139]
When trying to run with
`node main.js debug log facebook`
```
Unknown mode 'debug'
The modes avalible on your system are:
        - 'facebook'
        - 'skype'
        - 'slack'
        - 'test'
```
That's all.

**Comment by ParasDPain** [comment]
Use `node main.js --debug facebook`

The `debug` tag requires the `--` and unless I'm mistaken, `log` in the command won't work as well

**Comment by NekoKamiDesu** [comment]
@ParasDPain I see! In previous versions it worked and I just prepared a batch script so startup is easier and faster :)
Thanks for the info!

**Comment by ParasDPain** [comment]
Yea I myself faced this issue while merging recent changes. Speaking of scripts, I use a recursive shell script to automatically restart the bot unless exiting with code 0.

Do tell if there's a need for it. I'll post a gist

**Comment by NekoKamiDesu** [comment]
@ParasDPain I don't exactly have a need for it now, however feel free to post it :)

**Comment by mrkno** [comment]
Yeah, sorry about this. It was pushed into master in one of the newer features but it wasn't really announced. It was done to allow for positional independence with the new `--timestamp` option.

https://github.com/mrkno/Kassy/blob/master/doc/DebuggingAndLogging.md

**Comment by ParasDPain** [comment]
[Here's the script](https://gist.github.com/ParasDPain/4a1db68b71a7d51dc6844c774605f76f) I normally use to run Kassy. Looks like there's space for improvement with the `--log` and `--timestamp` tags

**Comment by NekoKamiDesu** [comment]
@ParasDPain 
[Here's](https://gist.github.com/NekoKamiDesu/65b4381babbc7ce7a940fc028bf1d06a) the one I use. Because of my unstable internet connection I have some ping tests in place to make sure that the internet connection is up. (and the whole thing is written in batch)
I never though of making sure its a crash though :smile:
