### ISSUE TITLE
Ideas for new Kassy modules, (before they fall out of my head)

### ISSUE THREAD

**Issue by Awarua-** [mrkno/Kassy#31]
!youtube <query>  "search the youtubes"
!sound <query> "slack specific using this lib https://github.com/caseyfw/slack-sounds would require porting to nodejs"
!emoji <words> "translate english to emoji https://github.com/notwaldorf/emoji-translate"

**Comment by Awarua-** [comment]
To add to the list,
!bugReport  "create and issue on github"
!todo list "keeps a list of things to do"

other functionality offered by hugh bot

**Comment by ParasDPain** [comment]
How about a Google search? either returns the google generated answer to the search or the top 3 result titles

**Comment by Awarua-** [comment]
I should update this,
Bug reporting has been implemented with Issue core module, https://github.com/mrkno/Kassy/blob/master/core/core_modules/issue.js although it looks like I forgot the documentation, whoops.

emoji translate has a kpm module here https://github.com/Awarua-/emoji-translate-kpm

Things like youtube and others would probably fall under the hubot compatibility layer https://github.com/mrkno/Kassy/issues/71

@ParasDPain For Google search there might be a module that can be cross integrated from hubot and there is an existing kpm LMGTFY module https://github.com/mrkno/KPM_LMGTFY
but feel free to write your own kpm modules :smile:

**Comment by ParasDPain** [comment]
I'm wondering whether we should make a wiki for all available KPM packages for Kassy? Thanks for the suggestion @Awarua- the package helped me build my own package for search on HummingBird.com (though it has issues being accessed by Kassy, [SO Question here](http://stackoverflow.com/questions/35328771/facebook-module-for-kassy-wont-run-even-though-all-instructions-are-being-follo)

**Comment by mrkno** [comment]
@ParasDPain KPM is a very new thing (as in the past few weeks) hence why there isn't any kind of wiki page yet. As for your problem, refering to the linked [HelloKassy project](https://github.com/mrkno/HelloKassy) from the [documentation](https://github.com/mrkno/Kassy/blob/master/doc/ModuleCreation.md) would probably be more useful tbh than the LMGTFY module, as it is simpler and has comments about how each method should work.

You StackOverflow question says that you get an error telling you to start kassy in debug mode. The documentation states how to do that [here](https://github.com/mrkno/Kassy/blob/master/doc/DebuggingAndLogging.md) (`node main.js debug ...`). This would give you full stack traces about what isn't working.
Additionally I tried running your module and do not get the unhandled error you do, just the output:
```
/humming anime
line 23
line 40
line 73
```

**Comment by ParasDPain** [comment]
@mrkno It's working for you? Awesome and thank you so much for the reply, I had already exhausted all my resources , as it turns out I was debugging it the wrong way. Thanks!

**Comment by mrkno** [comment]
Moved to https://github.com/mrkno/Kassy/wiki/Ideas-for-Modules
