### ISSUE TITLE
crash when connected to facebook group

### ISSUE THREAD

**Issue by gogoneykov123** [mrkno/Kassy#34]
so it is working fine , when i am using it in personal chat , but when i add the profile that is on the bot , the script crashes and gives me this error: 

ERR! ERROR in listen -->  TypeError: Cannot call method 'toString' of undefined
ERR! ERROR in listen -->      at Object.formatTyp (/home/kawaii/Kassy/node_modules/facebook-chat-api/utils.js:294:24)
ERR! ERROR in listen -->      at parsePackets (/home/kawaii/Kassy/node_modules/facebook-chat-api/src/listen.js:97:42)
ERR! ERROR in listen -->      at Array.forEach (native)
ERR! ERROR in listen -->      at /home/kawaii/Kassy/node_modules/facebook-chat-api/src/listen.js:86:12
ERR! ERROR in listen -->      at tryCatcher (/home/kawaii/Kassy/node_modules/facebook-chat-api/node_modules/bluebird/js/main/util.js:26:23)
ERR! ERROR in listen -->      at Promise._settlePromiseFromHandler (/home/kawaii/Kassy/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:507:31)
ERR! ERROR in listen -->      at Promise._settlePromiseAt (/home/kawaii/Kassy/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:581:18)
ERR! ERROR in listen -->      at Promise._settlePromises (/home/kawaii/Kassy/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:697:14)
ERR! ERROR in listen -->      at Async._drainQueue (/home/kawaii/Kassy/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:123:16)
ERR! ERROR in listen -->      at Async._drainQueues (/home/kawaii/Kassy/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:133:10)
ERR! ERROR in listen -->      at Async.drainQueues (/home/kawaii/Kassy/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:15:14)
ERR! ERROR in listen -->      at process._tickCallback (node.js:415:13)
ERR! ERROR in listen -->   [TypeError: Cannot call method 'toString' of undefined]
[TypeError: Cannot call method 'toString' of undefined]

Overall a great program/script here, but i'm mostly going to use if for a group chats , if you can fix it i would love it <3 . And i should add that some of the names of the people in the chat room are in Bulgarian, that uses diffrent alphabet than the english one. There are hole diffrrent.

**Comment by mrkno** [comment]
@gogoneykov123 what version of the facebook api has npm installed? It works fine with group chats here except for issue https://github.com/mrkno/Kassy/issues/33

**Comment by mrkno** [comment]
I managed to replicate using v1.0.3 of facebook-chat-api but it doesn't seem to exist in v1.0.2. For now just install v1.0.2 (because of https://github.com/mrkno/Kassy/commit/0fcda74c4be9e6a49fb4a540dd9869fcb7acbd68 you can just delete the folder `facebook-chat-api` from the `node_modules` directory, pull and then run `npm install` again and it will pull down the correct version).

For now as there is a workaround in place I will close this issue, I have opened an equivilent one on the api itself here: https://github.com/Schmavery/facebook-chat-api/issues/100.

**Comment by gogoneykov123** [comment]
Thanks I will try it now! :)
