### ISSUE TITLE
Kassy crashes upon receiving the thumbs up sticker on Facebook

### ISSUE THREAD

**Issue by ParasDPain** [mrkno/Kassy#78]
The sticker in question is the mouse clicked/finger tapped thumbs up. It is not available in the sticker store but provided under messenger's attachment-bar.

When sent (of any size) Kassy crashes with the following log message

```
ERR! ERROR in listen -->  TypeError: Cannot read property 'caption' of undefined
ERR! ERROR in listen -->      at _formatAttachment (H:\DEVIDE\Kassy-compiled\node_modules\facebook-chat-api\utils.js:155:29)
ERR! ERROR in listen -->      at H:\DEVIDE\Kassy-compiled\node_modules\facebook-chat-api\utils.js:250:12
ERR! ERROR in listen -->      at Array.map (native)
ERR! ERROR in listen -->      at formatAttachment (H:\DEVIDE\Kassy-compiled\node_modules\facebook-chat-api\utils.js:245:36)
ERR! ERROR in listen -->      at Object.formatMessage (H:\DEVIDE\Kassy-compiled\node_modules\facebook-chat-api\utils.js:267:18)
ERR! ERROR in listen -->      at parsePackets (H:\DEVIDE\Kassy-compiled\node_modules\facebook-chat-api\src\listen.js:134:35)
ERR! ERROR in listen -->      at Array.forEach (native)
ERR! ERROR in listen -->      at H:\DEVIDE\Kassy-compiled\node_modules\facebook-chat-api\src\listen.js:86:12
ERR! ERROR in listen -->      at tryCatcher (H:\DEVIDE\Kassy-compiled\node_modules\bluebird\js\main\util.js:26:23)
ERR! ERROR in listen -->      at Promise._settlePromiseFromHandler (H:\DEVIDE\Kassy-compiled\node_modules\bluebird\js\main\promise.js:507:31)
ERR! ERROR in listen -->      at Promise._settlePromiseAt (H:\DEVIDE\Kassy-compiled\node_modules\bluebird\js\main\promise.js:581:18)
ERR! ERROR in listen -->      at Promise._settlePromises (H:\DEVIDE\Kassy-compiled\node_modules\bluebird\js\main\promise.js:697:14)
ERR! ERROR in listen -->      at Async._drainQueue (H:\DEVIDE\Kassy-compiled\node_modules\bluebird\js\main\async.js:123:16)
ERR! ERROR in listen -->      at Async._drainQueues (H:\DEVIDE\Kassy-compiled\node_modules\bluebird\js\main\async.js:133:10)
ERR! ERROR in listen -->      at Immediate.Async.drainQueues [as _onImmediate] (H:\DEVIDE\Kassy-compiled\node_modules\bluebird\js\main\async.js:15:14)
ERR! ERROR in listen -->      at processImmediate [as _immediateCallback] (timers.js:383:17)
ERR! ERROR in listen -->   [TypeError: Cannot read property 'caption' of undefined]
undefined
```

I would argue this to be an important issue because users tend to use that thumbs-up quite often

**Comment by mrkno** [comment]
As this doesn't seem to be affecting us, can you test with a newer version of facebook-chat-api than the one specified within our package.json (change the line `"facebook-chat-api": "1.0.2"` to `"facebook-chat-api": "*"` in order to get the absoute latest version using `npm update`).

This is technically a bug in the [facebook-chat-api](https://github.com/Schmavery/facebook-chat-api/) project as opposed to Kassy, so I've reported it here: https://github.com/Schmavery/facebook-chat-api/issues/173.

**Comment by bsansouci** [comment]
Can you update `facebook-chat-api` and make sure it still happens. We fixed a ton of issues since 1.0.2.

**Comment by mrkno** [comment]
Still can't reproduce on 1.0.2 or 1.0.6, @ParasDPain can you confirm if a version bump helps? 

Facebook @ 1.0.6:
![1 0 6_facebook](https://cloud.githubusercontent.com/assets/6830312/12908360/234dac44-cf5b-11e5-87ce-9bdbc70022ba.jpg)
Messenger.com @ 1.0.6:
![1 0 6_messenger](https://cloud.githubusercontent.com/assets/6830312/12908361/258a819e-cf5b-11e5-9f33-ad90db58134f.jpg)

@Awarua- based on the above results are you fine with a version bump in package.json?

**Comment by Awarua-** [comment]
I am fine with it as it seems to satisfy the happy case and it was something we were going to have to deal with sooner or later.

**Comment by ParasDPain** [comment]
I updated the repo and installed with `"facebook-chat-api": "1.0.6"` and it has stopped crashing. The issue was fixed in the update indeed. Thanks for the feedback everyone
