### ISSUE TITLE
Error: ETIMEDOUT exception

### ISSUE THREAD

**Issue by ParasDPain** [mrkno/Kassy#79]
I can't pinpoint how this is caused but hopefully others will be able to recognize it (has happened a few times in 30 minutes of uptime). sometimes it just displays the exception and continues functioning (though have noticed it ignore commands after that) other times it just crashes.

It does only happen when someone is interacting with the Kassy, otherwise it runs fine

It did not happen when I ran it on my windows machine and later on an Ubuntu 15.04 VM. It happened while running on Kali 2.0 (Debian Jessie). Node is v5.5.0 and NPM is v3.3.2

```
ERR! Error in getUserInfo Error: ETIMEDOUT
ERR! Error in getUserInfo     at [object Object]._onTimeout (/root/Dev/Kassy/node_modules/request/request.js:956:15)
ERR! Error in getUserInfo     at Timer.listOnTimeout (timers.js:92:15)
ERR! Error in getUserInfo  { [Error: ETIMEDOUT]
ERR! Error in getUserInfo   cause: { [Error: ETIMEDOUT] code: 'ETIMEDOUT' },
ERR! Error in getUserInfo   isOperational: true,
ERR! Error in getUserInfo   code: 'ETIMEDOUT' }
Unhandled rejection Error: ETIMEDOUT
    at [object Object]._onTimeout (/root/Dev/Kassy/node_modules/request/request.js:956:15)
    at Timer.listOnTimeout (timers.js:92:15)
ERR! ERROR in listen -->  Error: ETIMEDOUT
ERR! ERROR in listen -->      at [object Object]._onTimeout (/root/Dev/Kassy/node_modules/request/request.js:956:15)
ERR! ERROR in listen -->      at Timer.listOnTimeout (timers.js:92:15)
ERR! ERROR in listen -->   { [Error: ETIMEDOUT]
ERR! ERROR in listen -->    cause: { [Error: ETIMEDOUT] code: 'ETIMEDOUT' },
ERR! ERROR in listen -->    isOperational: true,
ERR! ERROR in listen -->    code: 'ETIMEDOUT' }
undefined
```

There were other instances of similar errors as well, one of the notable ones is this

```

ERR! ERROR in listen -->  Error: read ECONNRESET
ERR! ERROR in listen -->      at exports._errnoException (util.js:856:11)
ERR! ERROR in listen -->      at TLSWrap.onread (net.js:544:26)
ERR! ERROR in listen -->   { [Error: read ECONNRESET]
ERR! ERROR in listen -->    cause: { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' },
ERR! ERROR in listen -->    isOperational: true,
ERR! ERROR in listen -->    code: 'ECONNRESET',
ERR! ERROR in listen -->    errno: 'ECONNRESET',
ERR! ERROR in listen -->    syscall: 'read' }
undefined
```

The errors has occured while `listen` `getUserInfo` and `sendMessage`

**Comment by mrkno** [comment]
Once again this belongs upstream in https://github.com/Schmavery/facebook-chat-api/.
Any errors that begin with "ERR!" within Kassy belong there (their API is the only integration that logs to the console in that way). So you know in future: we have a less verbose way of dealing with errors (`console.critical()` + debug cli arg) which would simply give you an error message unless you enabled stack traces.

It has already been reported here as:
https://github.com/mrkno/Kassy/issues/30

and seems to be similar to:
https://github.com/Schmavery/facebook-chat-api/issues/147

I would suggest reporting it upstream as there is not much we can do about it here :(
