### ISSUE TITLE
Captcha error

### ISSUE THREAD

**Issue by EdocTob** [mrkno/Kassy#81]
loaded modules: 8Ball, HelloKassy, anim, associate, fawlty, giphy, idea, insult, joke, karma, lithp, pickUp, pirate, profound, programmer, quote, runbot, slap, tictactoe, titleSet, vampire, vote, 
status flag: 1
core modules: creator.js, disable.js, help.js, issue.js, kpm.js, ping.js, restart.js, shutdown.js, update.js, uptime.js, 
modes: facebook,

**Comment by mrkno** [comment]
If this is the facebook security issue, log upstream in the facebook-chat-api project as it doesn't belong here. Otherwise more detail is required. Closing for now.
