### ISSUE TITLE
Modify commands in `exports.match` to avoid false matches for similar commands

### ISSUE THREAD

**Issue by ParasDPain** [mrkno/Kassy#82]
This is quite subjective and hence I haven't made a pull request for this. The issue is within the `exports.match` method's usage.

Most modules check for a command match with this `text.startsWith(commandPrefix + 'anim');`. The code is only checking for `/anim` as a prefix. The user can potentially pass in `/animatedHacks` and still have the module run; or pretty much anything that starts with `/anim`

Main side-effect is, this has limited the possible number of module commands within an instance of Kassy. For example, I can't create a module with the command `/anime` because all queries will be forwarded to `/anim` instead. 

A simple fix is to append a whitespace after the command, like this `text.startsWith(commandPrefix + 'anim ');`. I tried to add this in all modules, but some modules handle no queries with a specific message as well.

For example, `/quote` responds with a `Um.. what do you expect me to do?` message.

So is this fix the right thing to do here? Or is there a better solution?

This is regarding the main Kassy source, I know I can do whatever in my own fork :)

**Comment by mrkno** [comment]
This is a fundemental problem that has existed since the beginning and has been known about since the beginning (it is worth noting that it breaks other similar projects like hubot as well). The only solution where existing and future module flexibility is not broken is to modify the modules themselves - there will always be a case of crossover between commands between modules. If we eliminated the potential for this to happen entirely the concept of what this project is (a flexibile modular chat bot) would be missing the flexability part. I would say this can be 'partially' fixed, by adjusting modules that allow for adjustment but not those which don't. Also moving to regex in some situations could be better, so instead of:
```
return text.startsWith(commandPrefix + 'anim');
```
move to:
```
var prefix = commandPrefix.replace(/[-\/\\^$*+?.()|[\]{}]/g, '\\$&');
return text.test("/^" + prefix + "anim(?=\s|$)");
```
Obviously this is ugly and could be tidied up, however it leaves us with the same flexability as previously existed, allows for noop/blank arguments to be used and does not mess with any core prototypes.

Various module authors have also not written their modules to handle some situations when running and matching correctly which should be fixed at the same time. Eg. assuming a 1 character length prefix and/or trimmed strings.

**Comment by mrkno** [comment]
Just to clarify: @ParasDPain do you want to work on this issue or shall I add it to a future milestone?

**Comment by ParasDPain** [comment]
@mrkno Sorry about the late reply. Yeah I will go over all the present modules and apply this patch, and possibly add documentation inside "Creating Modules"

**Comment by ParasDPain** [comment]
@mrkno why don't we provide a method for `expprts.match ` to clean the input string rather than patching every  other module.

The method will output an array of command(s) (to support sub-commands) and the text.

By default the method will only extract the standard command. But the user can supply sub-commands to support their extraction as well. I'm assuming all commands/sub-commands will be prefixed with the commandPrefix as I've implemented it the humming module.

Since we are supplying the method, it will be totally optional for the user to implement it. They can choose to handle export.match however they want, preserving the flexibility of Kassy.

This should simplify instructions for the user as well. Moreover will hide all the dirty cleanup code in Kassy and give us total control over it (if the user decides to use it).

If you think it's a good idea, can you point me towards the core files where I'll be able to write this method?

**Comment by mrkno** [comment]
@ParasDPain I would have suggested wrapping my regex solution above in such a method anyway, but we should clean up existing modules while we are touching this code to prevent any related problems in future.

I would suggest abstracting this to a new file (located in core) which is `require.once()`ed in modules.js for each module, during the loading process.

_<I'll expand on this answer when I have some more time>_

**Comment by ParasDPain** [comment]
The existing modules definitely should be patched, that goes without saying. Looking forward to the expanded answer :)

**Comment by mrkno** [comment]
@ParasDPain sorry for the delay expanding - been a little busy.

The approach I would take reflecting on everything above is as follows:
- New file in `core` called say `match.js`.
- Within this file define a global helper function eg.`global.matchCommand`, the arguments of which and what it returns TBD (could be command, commandPrefix and the input, or have another helper function to check the return, whatever seems most logical at the time).
- In `platform.js`, beneath `require.reload('./prototypes.js');` add a similar line for reloading the created file.
- Modify each of the existing modules that you can to use the created method(s) as much as possible.

**Comment by ParasDPain** [comment]
Thanks for the detail, really helps since I'm not familiar with Node or the Kassy core :)

**Comment by ParasDPain** [comment]
Just an update;
I made some progress with the module but had to take a step back and really think about the best way for communicating the command structure between the `matchHelper` and the developer's module. The _tree-structure_ approach and the returned `json `seems like unnecessary complexity for both the objects. You can find the horrid code [here](https://github.com/ParasDPain/Kassy/blob/enhance/matchHelper/core/match.js)

Just adding this here as you have self-assigned the task. :)

**Comment by mrkno** [comment]
@ParasDPain I self assigned it cause I was already modifying all of the modules slightly for better hubot compatibility, sorry about that.

**Comment by ParasDPain** [comment]
@mrkno Thanks! I'm happy as long as the issue is being resolved :+1:
