### ISSUE TITLE
/math module for Kassy

### ISSUE THREAD

**Issue by kotAPI** [mrkno/Kassy#93]
Just an idea/enhancement for Kassy. 

/math 2+2
->4
/math 13*5
->65

PS: I'm new here, still haven't studied all the modules. I'm sorry if this feature already exists. Just puttin it out there.

**Comment by ParasDPain** [comment]
@kotAPI this feature already exists indeed. Not as direct but you can run JavaScript code in the `/runbot` module as `/runbot return 2+2;` and pretty perform any math that's supported by JavaScript. 

For future ideas, please submit them in the Wiki under [Ideas for Modules](https://github.com/mrkno/Kassy/wiki/Ideas-for-Modules).

**Comment by kotAPI** [comment]
Ah, sorry bout that.
ᐧ
